# Generated by Django 3.2.9 on 2021-11-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
